[package]
name = "noncryptor"
version = "0.1.1"
edition = "2021"
description = "Library for common encoding formats like base64 and URL"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
